# Generated by Django 5.2.7 on 2025-10-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habilidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="habilidades",
            name="usuario",
        ),
        migrations.AddField(
            model_name="usuario",
            name="habilidades",
            field=models.ManyToManyField(related_name="usuario", to="api.habilidade"),
        ),
        migrations.DeleteModel(
            name="Experiencia",
        ),
        migrations.DeleteModel(
            name="Habilidades",
        ),
    ]
